"""edit posts

Revision ID: 867571841bef
Revises: 0773db9b85c0
Create Date: 2024-01-08 19:09:56.414058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '867571841bef'
down_revision = '0773db9b85c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_ibfk_1', type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('posts_ibfk_1', 'users', ['poster_id'], ['id'])

    # ### end Alembic commands ###
